import '../definitions/enums.dart';
import 'package:json_annotation/json_annotation.dart';

part 'digital_growth_charts_chart_coordinates_response.g.dart'; // this file is generated by flutter pub run build_runner build

@JsonSerializable()
class DigitalGrowthChartsCentileLines {
  @JsonKey(name: 'centile_data')
  List<ReferenceData>? centileData;

  DigitalGrowthChartsCentileLines({this.centileData});

  factory DigitalGrowthChartsCentileLines.fromJson(Map<String, dynamic> json) {
    final List<dynamic>? centileDataList = json['centile_data'] as List<dynamic>?;
    final List<ReferenceData> parsedCentileData = [];

    if (centileDataList != null) {
      for (final item in centileDataList) {
        if (item is Map<String, dynamic>) {
          parsedCentileData.add(ReferenceData.fromJson(item));
        }
      }
    }
    return DigitalGrowthChartsCentileLines(centileData: parsedCentileData);
  }

  Map<String, dynamic> toJson() => _$DigitalGrowthChartsCentileLinesToJson(this);
}

@JsonSerializable()
class ReferenceData {
  @JsonKey(name: 'uk_who_child')
  SexMeasurementData? ukWhoChild;
  @JsonKey(name: 'uk90_child')
  SexMeasurementData? uk90Child;
  @JsonKey(name: 'uk_who_infant')
  SexMeasurementData? ukWhoInfant;
  @JsonKey(name: 'uk90_preterm')
  SexMeasurementData? uk90Preterm;

  ReferenceData({this.ukWhoChild, this.uk90Child, this.ukWhoInfant, this.uk90Preterm});

  factory ReferenceData.fromJson(Map<String, dynamic> json) =>
      _$ReferenceDataFromJson(json);

  Map<String, dynamic> toJson() => _$ReferenceDataToJson(this);
}

@JsonSerializable()
class SexMeasurementData {
  MaleMeasurements? male;
  FemaleMeasurements? female;

  SexMeasurementData({this.male, this.female});

  factory SexMeasurementData.fromJson(Map<String, dynamic> json) =>
      _$SexMeasurementDataFromJson(json);

  Map<String, dynamic> toJson() => _$SexMeasurementDataToJson(this);
}

@JsonSerializable()
class MaleMeasurements {
  List<CentileDataPoint>? height;
  List<CentileDataPoint>? weight;
  List<CentileDataPoint>? ofc;
  List<CentileDataPoint>? bmi;

  MaleMeasurements({this.height, this.weight, this.ofc, this.bmi});

  factory MaleMeasurements.fromJson(Map<String, dynamic> json) =>
      _$MaleMeasurementsFromJson(json);

  Map<String, dynamic> toJson() => _$MaleMeasurementsToJson(this);
}

@JsonSerializable()
class FemaleMeasurements {
  List<CentileDataPoint>? height;
  List<CentileDataPoint>? weight;
  List<CentileDataPoint>? ofc;
  List<CentileDataPoint>? bmi;

  FemaleMeasurements({this.height, this.weight, this.ofc, this.bmi});

  factory FemaleMeasurements.fromJson(Map<String, dynamic> json) =>
      _$FemaleMeasurementsFromJson(json);

  Map<String, dynamic> toJson() => _$FemaleMeasurementsToJson(this);
}

@JsonSerializable()
class CentileDataPoint {
  double? sds;
  double? centile;
  List<DataPointValue>? data;

  CentileDataPoint({this.sds, this.centile, this.data});

  factory CentileDataPoint.fromJson(Map<String, dynamic> json) =>
      _$CentileDataPointFromJson(json);

  Map<String, dynamic> toJson() => _$CentileDataPointToJson(this);
}

@JsonSerializable()
class DataPointValue {
  double? l;
  double? x;
  double? y;

  DataPointValue({this.l, this.x, this.y});

  factory DataPointValue.fromJson(Map<String, dynamic> json) =>
      _$DataPointValueFromJson(json);

  Map<String, dynamic> toJson() => _$DataPointValueToJson(this);
}