#!/bin/bash -e

# These should match the list in deploy-testing.yml
cat << EOF > .env
DGC_BASE_URL=${DGC_BASE_URL}
DGC_API_KEY=${DGC_API_KEY}
MICROSOFT_LOGIN_CLIENT_ID=${MICROSOFT_LOGIN_CLIENT_ID}
MICROSOFT_LOGIN_ISSUER=${MICROSOFT_LOGIN_ISSUER}
EOF

flutter pub get

flutter test

# Android
flutter build appbundle --release \
  --build-number ${BUILD_NUMBER}