#!/bin/bash -e

DART_DEFINES_ARGS=$1 # Capture dart-define arguments

flutter pub get
flutter test

# Android
flutter build appbundle \
  --build-number ${BUILD_NUMBER} \
  --dart-define=API_URL=$API_URL \
  --dart-define=API_KEY=$API_KEY
