#!/bin/bash -e

# These should match the list in pr-check.yml
cat << EOF > .env
DGC_BASE_URL=${DGC_BASE_URL}
DGC_API_KEY=${DGC_API_KEY}
EOF

flutter pub get

dart format --output=none --set-exit-if-changed .

flutter analyze

flutter test

# Android
flutter build apk \
    --debug \
    --build-number "$BUILD_NUMBER"
