name: Build app and release to test users

on:
  merge:
    branches: [main]
  workflow_dispatch:



permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # latest as at April 2025

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Extract version from pubspec.yaml and set build number (Android)
        id: get_version_android
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          BUILD_NUMBER=$GITHUB_RUN_NUMBER

          echo "Detected Android Version Name: $VERSION_NAME"
          echo "Generated Android Build Number: $BUILD_NUMBER"

          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Create dummy .env for CI build (if needed by pubspec.yaml assets)
        run: touch .env # Creates an empty .env file: this is necessary to satisfy pubspec.yaml assets declaration, but it is empty so dart-defines will be used

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/keystore.jks

      - name: Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Run CI script (test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          API_URL: ${{ secrets.DGC_BASE_URL }}
          API_KEY: ${{ secrets.DGC_API_KEY }}
        run: |
          DEFINES_FOR_SCRIPT=""
          if [ -n "${{ secrets.DGC_BASE_URL }}" ]; then
            DEFINES_FOR_SCRIPT="--dart-define=DGC_BASE_URL=${{ secrets.DGC_BASE_URL }} $DEFINES_FOR_SCRIPT"
          fi
          if [ -n "${{ secrets.DGC_API_KEY }}" ]; then
            DEFINES_FOR_SCRIPT="--dart-define=DGC_API_KEY=${{ secrets.DGC_API_KEY }} $DEFINES_FOR_SCRIPT"
          fi
          ./s/ci "$DEFINES_FOR_SCRIPT"

      - id: authenticate
        name: Authenticate with Google
        uses: google-github-actions/auth@v2 # latest as at April 2025
        with:
          service_account: rcpch-growth-charts-app@rcpch-growth-charts-app.iam.gserviceaccount.com
          workload_identity_provider: projects/221963061860/locations/global/workloadIdentityPools/github/providers/rcpch-growth-charts-app
          create_credentials_file: true

      - name: Upload to Internal Test Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.authenticate.outputs.credentials_file_path }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          packageName: uk.ac.rcpch.digital_growth_charts_app
          track: internal

  build-and-push-web:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # latest as at April 2025

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Create dummy .env for CI build (if needed by pubspec.yaml assets)
        run: touch .env # Creates an empty .env file: this is necessary to satisfy pubspec.yaml assets declaration, but it is empty so dart-defines will be used

      - name: Run CI script (test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          API_URL: ${{ secrets.DGC_BASE_URL }}
          API_KEY: ${{ secrets.DGC_API_KEY }}
        run: |
          DEFINES_FOR_SCRIPT=""
          if [ -n "${{ secrets.DGC_BASE_URL }}" ]; then
            DEFINES_FOR_SCRIPT="--dart-define=DGC_BASE_URL=${{ secrets.DGC_BASE_URL }} $DEFINES_FOR_SCRIPT"
          fi
          if [ -n "${{ secrets.DGC_API_KEY }}" ]; then
            DEFINES_FOR_SCRIPT="--dart-define=DGC_API_KEY=${{ secrets.DGC_API_KEY }} $DEFINES_FOR_SCRIPT"
          fi
          ./s/ci "$DEFINES_FOR_SCRIPT"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web