name: Build app and release to test users (Android & Web)

on:
  push:
    branches: [main] # Or perhaps on: release: types: [published] if you want this for releases
  workflow_dispatch:

permissions:
  id-token: write # For Google Play auth
  contents: write # For committing to repo for GitHub Pages for actions/deploy-pages
  pages: write    # Required for actions/deploy-pages

jobs:
  build-and-publish-android:
    runs-on: ubuntu-latest
    # ============================
    # ANDROID BUILD AND DEPLOY
    # ============================
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Extract version from pubspec.yaml and set build number (Android)
        id: get_version_android
        run: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          BUILD_NUMBER=$GITHUB_RUN_NUMBER

          echo "Detected Android Version Name: $VERSION_NAME"
          echo "Generated Android Build Number: $BUILD_NUMBER"

          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/keystore.jks

      - name: Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Run CI script (test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          DGC_BASE_URL: ${{ secrets.DGC_BASE_URL }}
          DGC_API_KEY: ${{ secrets.DGC_API_KEY }}
          MICROSOFT_LOGIN_CLIENT_ID: ${{ secrets.MICROSOFT_LOGIN_CLIENT_ID }}
          MICROSOFT_LOGIN_OAUTH_SERVER: ${{ secrets.MICROSOFT_LOGIN_OAUTH_SERVER }}
        run: ./s/ci android

      - id: authenticate
        name: Authenticate with Google
        uses: google-github-actions/auth@v3
        with:
          service_account: rcpch-growth-charts-app@rcpch-growth-charts-app.iam.gserviceaccount.com
          workload_identity_provider: projects/221963061860/locations/global/workloadIdentityPools/github/providers/rcpch-growth-charts-app
          create_credentials_file: true

      - name: Upload to Internal Test Track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.authenticate.outputs.credentials_file_path }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          packageName: uk.ac.rcpch.digital_growth_charts_app
          track: internal

  # ============================
  # WEB BUILD AND DEPLOY
  # ============================
  build-and-deploy-web:
    runs-on: ubuntu-latest
    name: Build and Deploy Web App to GitHub Pages

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
          cache: true

      - name: Run CI script (test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          DGC_BASE_URL: ${{ secrets.DGC_BASE_URL }}
          DGC_API_KEY: ${{ secrets.DGC_API_KEY }}
          MICROSOFT_LOGIN_CLIENT_ID: ${{ secrets.MICROSOFT_LOGIN_CLIENT_ID }}
          MICROSOFT_LOGIN_OAUTH_SERVER: ${{ secrets.MICROSOFT_LOGIN_OAUTH_SERVER }}
        run: ./s/ci web

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory containing the static assets to be deployed.
          # Flutter web builds to 'build/web' by default.
          path: './build/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
