name: Build and test app on PRs

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      - name: Run PR check script (check formatting, analyze, test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          DGC_BASE_URL: ${{ secrets.DGC_BASE_URL }}
          DGC_API_KEY: ${{ secrets.DGC_API_KEY }}
          # Make sure to add to the s/pr-check script and deploy-testing.yml too
        run: s/pr-check