name: Build and test app on PRs

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # latest as at April 2025

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Create dummy .env for CI build (if needed by pubspec.yaml assets)
        run: touch .env # Creates an empty .env file

      - name: Run PR check script (test and build)
        env:
          BUILD_NUMBER: ${{github.run_number}}
          DGC_BASE_URL: ${{ secrets.DGC_BASE_URL }}
          DGC_API_KEY: ${{ secrets.DGC_API_KEY }}
        run: s/pr-check